### ISSUE TITLE
traefik proxy >> docker-compose.yml

### ISSUE THREAD

**Issue by jujes** [jojomi/docker-hugo#17]
Hi, someone know how deploy this docker hugo version using traefik as proxy?
here my file:

**docker-compose.yml**

```
version: '2'

services:
  hugo:
    image: jojomi/hugo:latest
    volumes:
      - ./src/:/src
      - ./output/:/output
    command: hugo server --bind 0.0.0.0
    environment:
      - HUGO_REFRESH_TIME=3600
      - HUGO_THEME=mytheme
      - HUGO_BASEURL=mydomain.com
    restart: always

  web:
    image: jojomi/nginx-static
    volumes:
      - ./output:/var/www
    environment:
      - VIRTUAL_HOST=mydomain.com
    labels:
      - "traefik.enable=true"
      - "traefik.backend=mydomain.com"
      - "traefik.frontend.rule=Host:mydomain.com, www.mydomain.com"
      - "traefik.docker.network=docker_webgateway"
    ports:
      - 80
    restart: always
    networks:
      - docker_webgateway

networks:
  docker_webgateway:
    external:
      name: docker_webgateway
```

thanks in advance
