### ISSUE TITLE
Changes by IDE in mounted directory not being watched?

### ISSUE THREAD

**Issue by saitho** [jojomi/docker-hugo#37]
Hi,

I'm currently using this docker-compose file to spin up my local development environment:

```
version: '2'
services:
  hugo_dev:
    image: jojomi/hugo:latest
    ports:
      - "1313:1313"
    environment:
      - HUGO_WATCH=1
    volumes:
      - ./src/:/src
```

When I edit a file in my IDE (IntelliJ) the file on the Docker container is updated, but Hugo does not recompile... When I log onto the container, open the file with `vi` and just write it again without making any changes Hugo recompiles and refreshes the site.

Any ideas how to fix that? :(
