### ISSUE TITLE
How do I point the container at my docker files?

### ISSUE THREAD

**Issue by amca01** [jojomi/docker-hugo#50]
I am a docker newbie; previously my hugo blog was served by apache.  My docker system has everything in a directory called "docker":

```
docker>
    Dockerfile
    traefik.toml
    docker-compose.yml
    acme.json
    whats_this>
        config.toml
        content>
        data>
        layout>s
        public>
        static>
        themes>
```

So `whats_this` contains all my blog files; the original apache configuration simply pointed to the `public` directory.  I ran `hugo` on my local machine, and when everything was just right I used `rsync` to copy all the files to my VPS.

But I'm having extraordinary difficulty getting this done in docker!  There's a million different web pages and example files showing how to do it. but I always seem to get mine not to work.  I'm using traefik as a reverse proxy, so I shouldn't need a call to nginx.  The section of my `docker-compose.yml` file is this:

```
  hugo:
    image: jojomi/hugo:latest
    ports:
      - "1313:1313"
    volumes:
      - ${PWD}/whats_this/:/src
      - ./output/:/output
    networks:
      - proxy
    environment:
      - HUGO_REFRESH_TIME=3600
      - HUGO_THEME=blackburn
      - HUGO_BASEURL=blog.my.vps.net
    restart: always
    labels:
      - traefik.enable=true
      - traefik.backend=hugo
      - traefik.docker.network=proxy      
      - traefik.port=8080
      - traefik.frontend.rule=Host:blog.my.vps.net
```
However, this just throws up a `404 Page not found` error; or sometimes a `Gateway timeout` error.  I'm getting frustrated by this!  What should be a dead easy task has grown into a monster.

Anyway, if anybody can fling a useful suggestion about how I might either find out what's going wrong, or point to any obvious errors in the file above, I'd be very grateful!

**Comment by jojomi** [comment]
I am running a similar setup, but when you are not using hugo as the webserver, you will have to use another container for serving your content. As far as I know traefik is not capable of doing that but is just proxying the request to a "backend" that does the webserving.

This is my `docker-compose.yml`:

```
version: '3.3'

services:

  caddy:
    image: jojomi/caddy:0.11.0
    volumes:
      - "./data/app:/app"
      - "./data/src:/src"
      - "./data/output:/output:ro"
    networks:
      - domainproxy_public_services
    ports:
      - "2015"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${FQDN}"
      - "traefik.frontend.rule=Host:${FQDN}"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.docker.network=domainproxy_public_services"
      - "traefik.acme.email=certs@${FQDN}"
    command: /opt/caddy -conf=/app/Caddyfile
    restart: unless-stopped

  hugo:
    image: jojomi/hugo:0.46
    volumes:
      - "./data/src:/src:ro"
      - "./data/output:/output"
    environment:
      - HUGO_REFRESH_TIME=3600
      - HUGO_THEME=material
      - HUGO_BASEURL=https://whatever.com
    restart: unless-stopped

networks:
  domainproxy_public_services:
    external: true
```

You also need a `.env` file containing `FQDN=whatever.com`.

Hope this helps you!

**Comment by amca01** [comment]
Thank you very much!  I'll have a play with your setup... I'm already running another web app (Kanboard: a kanban application) in a container, and it works fine.  The main thing is that the docker-compose file has to include the name of the docker network, called "proxy" on my system.  This seems to automagically mean that traefik can route traffic to it.  Beyond that I'm a bit at sea...  Thanks again!

**Comment by amca01** [comment]
I should add that I have also tried to create a docker image with the Dockerfile:

    FROM nginx:alpine
    COPY ./whats_this/public /usr/share/nginx/html

which I supposed should create a container with nginx for serving the blog.  But getting Hugo, traefik, docker-compose, etc all playing together has become for me an impossible task of labyrinthine complexity.  Sigh...

**Comment by jojomi** [comment]
I can add my matching `docker-compose.yml` for the traefik part for your reference, perhaps that helps getting you started:

```
version: '3.3'

services:
  proxy:
    image: traefik:1.6
    command: --logLevel=WARNING # --web
    networks:
      - public_services
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml:ro
      - ./acme:/etc/acme:rw
    restart: unless-stopped

networks:
  public_services:
    driver: bridge
```
