### ISSUE TITLE
How to stop hugo from appending :1313 to everything?

### ISSUE THREAD

**Issue by kstenerud** [jojomi/docker-hugo#66]
When I create a site and try to serve it, every link within the site has port 1313 appended to it (it's like this in the actual generated content). I've set `HUGO_BASEURL` to no avail :/

docker-compose.yml:
```yaml
version: '3.3'

volumes:
  generated_html:

services:

  web:
    restart: always
    image: nginx
    container_name: ts-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - generated_html:/usr/share/nginx/html:ro

  hugo:
    restart: always
    image: jojomi/hugo:latest
    container_name: ts-hugo
    volumes:
      - /home/site/blog:/src
      - generated_html:/output
    environment:
      - HUGO_WATCH=true
      - HUGO_THEME=beg
      - HUGO_BASEURL=redacted.net
```
